"""Criação da tabela User

Revision ID: 527af0f5abc8
Revises: 
Create Date: 2019-07-28 09:30:56.363921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527af0f5abc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=64), nullable=True),
    sa.Column('user_useremail', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_useremail'), 'user', ['user_useremail'], unique=True)
    op.create_index(op.f('ix_user_user_username'), 'user', ['user_username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_useremail'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
